### ISSUE TITLE
Actions (Email) not firing from java deployments.

### ISSUE THREAD

**Issue by sushilraje** [Azure/remote-monitoring-services-java#132]
# Type of issue 
- [x] Bug
- [ ] New feature
- [ ] Improvement

# Description 
The email action is not working as expected. When the rule is triggered it is expected to fire an email. But I haven't received any email even after multiple rule firings. The info level logs indicate rules has been triggered, but there are no logs related to firing of an email or action getting executed.

# Screenshot 

# Steps to reproduce 
1. Create a java basic or standard deployment.
2. Create a rule configured with an email trigger.

# Expected behavior 
...

# Current behavior 
...

# Known workarounds 
...

# Possible solution 
...

# Context and Environment
* Operating System: ...
* GitHub branch: ...
* JRE & JDK: ...
* SBT (version): ...

**Comment by jillcary** [comment]
The management API call for the office365 logic app connector is returning an error:
```
GET https://management.azure.com/subscriptions/<subid>/resourceGroups/<rg-name>/providers/Microsoft.Web/connections/office365-connector/extensions/proxy/testconnection?api-version=2016-06-01
```
```
{
    "status": 401,
    "source": "https://logic-apis-eastus.token.azure-apim.net:443/tokens/logic-apis-eastus/office365/ba8faa96297c40ffa300167e26ce7fa1/exchange",
    "message": "Error from token exchange: Runtime call was blocked because connection has error status: Enabled| Error, and office365 is in the block list. Connection errors: [ParameterName: token, Error: Code: Unauthenticated, Message: 'This connection is not authenticated.']"
}
```
