### ISSUE TITLE
Can't get devices from iothub-manager

### ISSUE THREAD

**Issue by GauthierV** [Azure/remote-monitoring-services-java#138]
# Type of issue
- [x] Bug
- [ ] New feature
- [ ] Improvement

# Description

Hi, i use iothub-manager microservice, and when i try to get all my devices with a get request on url/v1/devices , i get an error instead of my list of devices. I can get single device but not all.

# Screenshot
Here is the stack returned by the iothub-manager : 
{
ExceptionType: "java.lang.IllegalArgumentException",
ExceptionMessage: "Key cannot contain illegal unicode control characters '.', '$', ' '",
Message: "An error has occurred",
StackTrace: [
{
methodName: "<init>",
fileName: "Pair.java",
lineNumber: 29,
className: "com.microsoft.azure.sdk.iot.service.devicetwin.Pair",
nativeMethod: false
},
{
methodName: "mapToSet",
fileName: "DeviceTwinDevice.java",
lineNumber: 598,
className: "com.microsoft.azure.sdk.iot.service.devicetwin.DeviceTwinDevice",
nativeMethod: false
},
{
methodName: "getTags",
fileName: "DeviceTwinDevice.java",
lineNumber: 218,
className: "com.microsoft.azure.sdk.iot.service.devicetwin.DeviceTwinDevice",
nativeMethod: false
},
{
methodName: "<init>",
fileName: "TwinServiceModel.java",
lineNumber: 61,
className: "com.microsoft.azure.iotsolutions.iothubmanager.services.models.TwinServiceModel",
nativeMethod: false
},
{
methodName: "lambda$getTwinByQueryAsync$7",
fileName: "Devices.java",
lineNumber: 450,
className: "com.microsoft.azure.iotsolutions.iothubmanager.services.Devices",
nativeMethod: false
},
{
methodName: "forEach",
fileName: "ArrayList.java",
lineNumber: 1249,
className: "java.util.ArrayList",
nativeMethod: false
},
{
methodName: "getTwinByQueryAsync",
fileName: "Devices.java",
lineNumber: 450,
className: "com.microsoft.azure.iotsolutions.iothubmanager.services.Devices",
nativeMethod: false
},
{
methodName: "lambda$queryAsync$2",
fileName: "Devices.java",
lineNumber: 159,
className: "com.microsoft.azure.iotsolutions.iothubmanager.services.Devices",
nativeMethod: false
},
{
methodName: "uniHandle",
fileName: "CompletableFuture.java",
lineNumber: 822,
className: "java.util.concurrent.CompletableFuture",
nativeMethod: false
},
{
methodName: "tryFire",
fileName: "CompletableFuture.java",
lineNumber: 797,
className: "java.util.concurrent.CompletableFuture$UniHandle",
nativeMethod: false
},
{
methodName: "postComplete",
fileName: "CompletableFuture.java",
lineNumber: 474,
className: "java.util.concurrent.CompletableFuture",
nativeMethod: false
},
{
methodName: "complete",
fileName: "CompletableFuture.java",
lineNumber: 1962,
className: "java.util.concurrent.CompletableFuture",
nativeMethod: false
},
{
methodName: "lambda$getDevicesAsync$2",
fileName: "RegistryManager.java",
lineNumber: 316,
className: "com.microsoft.azure.sdk.iot.service.RegistryManager",
nativeMethod: false
},
{
methodName: "call",
fileName: "Executors.java",
lineNumber: 511,
className: "java.util.concurrent.Executors$RunnableAdapter",
nativeMethod: false
},
{
methodName: "run",
fileName: "FutureTask.java",
lineNumber: 266,
className: "java.util.concurrent.FutureTask",
nativeMethod: false
},
{
methodName: "runWorker",
fileName: "ThreadPoolExecutor.java",
lineNumber: 1142,
className: "java.util.concurrent.ThreadPoolExecutor",
nativeMethod: false
},
{
methodName: "run",
fileName: "ThreadPoolExecutor.java",
lineNumber: 617,
className: "java.util.concurrent.ThreadPoolExecutor$Worker",
nativeMethod: false
},
{
methodName: "run",
fileName: "Thread.java",
lineNumber: 745,
className: "java.lang.Thread",
nativeMethod: false
}
]
}

# Current behavior

I use the storage-adapter microservice with cosmos DB and everything is well connected.
I didn't modify the code. I managed to make it work for one day and a day later, it's not working anymore.
I use it in an Azure VM with Docker and localy on Intelij Idea Comunity Edition. Both worked well yesterday, both don't work anymore.

The service status is ok : 
Status: {IsHealthy: true,
Message: "Alive and well!"},

When i try to get /v1/devices i got the stack error so id deleted all my iot edge and my iot devices.
Then, when i try to get /v1/devices i got : 
Items: [ ],
ContinuationToken: null,
$metadata: {
$type: "DeviceList;1",
$uri: "/v1/devices"
}

As soon as i create a new iot edge or iot device in my iothub, i got the stack. I also got this log every 10 seconds in the app : 
[warn] c.m.a.i.i.s.DeviceProperties - Some underlying service is not ready. Retry after %d seconds.10
This warn is here in the code : 
https://github.com/Azure/remote-monitoring-services-java/blob/f88960e6d0654e55d3017dcb66c2971db374707e/iothub-manager/app/com/microsoft/azure/iotsolutions/iothubmanager/services/DeviceProperties.java#L183
As soon as i delete all iot devices, the log stop.

The services worked for a day and i didn't notice if i changed anything but apparently something changed, and i can't make sense of those errors.

Thank's for your help.

Edit : i deployed the service in dotnet and with the same data, i t works well.

# Known workarounds 
...

# Possible solution 
...

# Context and Environment
* Operating System: linux server 18.04
* GitHub branch: master
* JRE & JDK: 1.8
* Docker version : 18.09.2

**Comment by chmagitt** [comment]
Hello, 
Can we consider  the bug  is fixed now and we can go to production ?
thanks for you support
