### ISSUE TITLE
Use "set -e" instead of passing -e in the shebang

### ISSUE THREAD

**Issue by jillcary** [Azure/remote-monitoring-services-java#22]
https://github.com/Azure/device-telemetry-java/issues/108

# Type of issue 

- [x] Bug
- [ ] New feature
- [ ] Enhancement

# Description 

When the shell script executed in Git Bash on Windows environment, it will report an error
```
/usr/bin/env: ‘bash -e’: No such file or directory
```
It can be fixed by change
```
#!/usr/bin/env bash -e
```
to
```
#!/usr/bin/env bash 
set -e
```

**Comment by ppathan** [comment]
Dupe of #35
