### ISSUE TITLE
Use "set -e" instead of passing -e in the shebang 

### ISSUE THREAD

**Issue by molly-moen** [Azure/remote-monitoring-services-java#35]
# Type of issue 

- [x] Bug
- [ ] New feature
- [ ] Enhancement

# Description 

When the shell script executed in Git Bash on Windows environment, it will report an error
```
/usr/bin/env: ‘bash -e’: No such file or directory
```
It can be fixed by change
```
#!/usr/bin/env bash -e
```
to
```
#!/usr/bin/env bash 
set -e
```

**Comment by molly-moen** [comment]
There is a PR on the old repo that does this work: https://github.com/Azure/iothub-manager-java/pull/95

**Comment by ppathan** [comment]
@sushilraje Can we bring this PR in this repo?
