### ISSUE TITLE
JobResponse EndTimeUtc is DateTime MaxValue instead of null when JobStatus is Running

### ISSUE THREAD

**Issue by jillcary** [Azure/remote-monitoring-services-java#39]
# Type of change? 
- [x] Bug fix
- [ ] New feature
- [ ] Enhancement
- [ ] Breaking change (breaks backward compatibility)

# Description, Context, Motivation 
The IoT Hub returns a date that is always 12/30/9999 when the job hasn't completed yet. 
This fix returns null for the end time when a job hasn't yet finished running. 

![image](https://user-images.githubusercontent.com/3317135/39500769-bc9e3a22-4d6b-11e8-9c1e-5219f2b1fc41.png)

**Related Items**

1. PR for fix in dotnet [here](https://github.com/Azure/iothub-manager-dotnet/pull/117)
2. Issue filed with the SDK [here](https://github.com/Azure/azure-iot-sdk-csharp/issues/467)

**Checklist:**

- [x] All tests passed
- [x] The code follows the code style and conventions of this project
- [ ] The change requires a change to the documentation
- [ ] I have updated the documentation accordingly

**Comment by asdonald** [comment]
@jillcary assigning this for the next milestone.

**Comment by avneet723** [comment]
@jillcary was this updated for Java as well? If so, can we close?

**Comment by ppathan** [comment]
@jillcary What's the status? Is this done and can it be closed?
