### ISSUE TITLE
Firmware update on devices doesn't work

### ISSUE THREAD

**Issue by isaac73** [Azure/remote-monitoring-services-java#51]
### Steps to Repro

1. Go to WEbUI
2. Go to devices Tab
3. Click check box of  any device
4. Click Jobs
5. Select Method
6. Select Firmeware update
7. Fill out the other required fields
8. Submit

### Expected:

1. Job Submited successfully
2. If click that job, it will take you to maintenance page
3. Job should be complete in few seconds.
4. If you go back to devices page, the device firmware is not updated

### Actual:

1. Job Submited successfully
2. If click that job, it will take you to maintenance page
3. Job is running forever and Firmaware version is not updated in the device

**Comment by ppathan** [comment]
no repro
