### ISSUE TITLE
Device Telemetry - Do model validation in API side for ruleModel

### ISSUE THREAD

**Issue by isaac73** [Azure/remote-monitoring-services-java#67]
# Type of issue 
- [ ] Bug
- [ ] New feature
- [x] Improvement

# Description 

we should validate models before invoking ToServiceModel. You can see an example here:

https://github.com/Azure/device-simulation-dotnet/blob/master/WebService/v1/Controllers/SimulationsController.cs#L71
https://github.com/Azure/device-simulation-dotnet/blob/master/WebService/v1/Models/SimulationApiModel/SimulationApiModel.cs#L123

Also, update unit test

**Comment by ppathan** [comment]
@isaac73 Is this done?

**Comment by ppathan** [comment]
Done.
